#!/usr/bin/env bash
# this is a bash script that transfers a file from
# out client to a server

file=$1
server_ip=$2
username=$3
ssh_key=$4

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file" "$username@$server_ip":~/
fi
