#!/usr/bin/env bash
# this is a bash script that;
# - install nginx
# - configure nginx to return "hello world!"
# - configure nginx to have a /redirect_me page

# install nginx
sudo apt-get update
sudo apt-get -y install nginx

# enable firewall on server
#sudo ufw enable
# configure firewall to allow port 80
#sudo ufw allow 'Nginx  HTTP'

# configure default return page
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# configure nginx server /redirect_me page
replacement_string="server_name _;\n\n\trewrite \^\/redirect_me https\:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
search_pattern="server_name _;"

sudo sed -i "s/$search_pattern/$replacement_string/g" /etc/nginx/sites-enabled/default

# restart nginx server
sudo service nginx restart
