#!/usr/bin/env bash
# fixes the bug in my server

# update and upgrade packages
sudo apt update
sudo apt upgrade

# install nginx
sudo apt install nginx

# start web server service
sudo service nginx start
